<?php

namespace App\Support;

class ProductCatalog
{
	public static function all(): array
	{
		return [
			[
				'slug'        => 'tree-mix-mico',
				'name'        => 'Tree Mix MICO',
				'tagline'     => 'Inoculante de micorrizas',
				'short'       => 'Expande la red radicular. Potencia la absorción de agua y nutrientes desde el trasplante.',
				'description' => 'Inoculante micorrízico de alta concentración que coloniza las raíces y extiende el sistema radicular. Mejora la absorción de fósforo, agua y micronutrientes, reduciendo el estrés en trasplante y acelerando el establecimiento.',
				'composition' => 'Glomus sp 1 × 10⁹ UFC/ml.',
				'features'    => [
					'Colonización radicular desde el día 1',
					'Mayor absorción de fósforo y agua',
					'Reduce estrés por trasplante',
					'Compatible con todos los sustratos',
					'Filtra absorción de metales pesados',
					'Aumenta capacidad de retener humedad',
					'Ayuda a la asimilación del fósforo',
				],
				'badge'                => 'premium',
				'order'               => 1,
				'image'               => 'logos_productos/LOGO MICO.png',
				'dosage'              => [
					'ml_per_liter' => 1,
					'range'        => '1 a 3 ml según efecto deseado',
					'applications' => 4,
					'timing'       => 'Solo ante situaciones de siembra y trasplante.',
				],
				'application_schedule' => ['stage' => 'trasplante', 'frequency' => 'puntual'],
			],
			[
				'slug'        => 'tree-mix-pro',
				'name'        => 'Tree Mix PRO',
				'tagline'     => 'Bioestimulante base',
				'short'       => 'Estimula y protege en todo el ciclo. Fórmula base de la línea profesional.',
				'description' => 'Bioestimulante y promotor de crecimiento con control biológico contra patógenos. Al estar inoculado y ya activado, genera resultados visibles a las 24 hs de aplicado. Potencia la absorción de nutrientes, garantiza frondosidad y actúa como preventivo contra hongos.',
				'composition' => 'Trichoderma harzianum 2,6 × 10⁷ UFC/ml y aminoácidos vegetales.',
				'features'    => [
					'Resultados visibles a las 24 hs',
					'Garantiza frondosidad generando nuevos brotes',
					'Protege y fortalece previniendo adversidades',
					'Estimulante del sistema inmunológico',
					'Mejora la actividad fotosintética',
					'Potencia la permeabilidad celular y absorción de agua',
					'Acelera la recuperación ante estrés',
					'Favorece el equilibrio microbiológico del suelo',
					'Brinda notable desarrollo radicular',
					'Revitaliza ante cualquier tipo de adversidad',
				],
				'badge'                => 'exclusivo',
				'order'               => 2,
				'image'               => 'logos_productos/LOGO PRO.png',
				'dosage'              => [
					'ml_per_liter' => 3,
					'range'        => '3 a 5 ml según efecto deseado',
					'applications' => 'semanal',
					'timing'       => 'No más de 1 vez por semana durante la etapa vegetativa.',
				],
				'application_schedule' => ['stage' => 'todo el ciclo', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'tree-mix-n',
				'name'        => 'Tree Mix N',
				'tagline'     => 'Complemento vegetativo',
				'short'       => 'Complemento nitrogenado para etapa vegetativa. Potencia el crecimiento y el follaje.',
				'description' => 'Complemento de nutrición biomineral para etapa vegetativa. Producto ideal para cultivos LED por su aporte de calcio. Es el complemento ideal ante el uso de bioestimulantes, para nutrir a la planta y que pueda crecer con vigorosidad.',
				'composition' => 'Nitrógeno 5, calcio y ácidos húmicos.',
				'features'    => [
					'Ayuda a incrementar el tamaño de la planta',
					'Produce desarrollo de células vegetales',
					'Revitaliza hojas con carencia de nitrógeno',
					'Aporta color verde saludable potenciando la clorofila',
					'Ideal para cultivos LED por su aporte de calcio',
					'Complementa el programa PRO',
				],
				'badge'                => 'premium',
				'order'               => 3,
				'image'               => 'logos_productos/LOGO N.png',
				'dosage'              => [
					'ml_per_liter' => 4,
					'range'        => '4 ml por litro de agua',
					'applications' => 'quincenal',
					'timing'       => 'Una vez cada 15 días en etapa vegetativa.',
				],
				'application_schedule' => ['stage' => 'vegetativo', 'frequency' => 'quincenal'],
			],
			[
				'slug'        => 'biok-nn',
				'name'        => 'Tree Mix BioK-NN',
				'tagline'     => 'Producto exclusivo',
				'short'       => 'Aumenta cannabinoides hasta un 50% más. Fija nitrógeno atmosférico. Optimiza el rendimiento en etapas vegetativas y de floración.',
				'description' => 'Producto biológico 100% natural que transforma los cultivos mediante fijación biológica de nitrógeno atmosférico. Potencia cannabinoides hasta un 50% más, mejora la absorción de nutrientes y optimiza el ROI en producción. Reemplaza los cultivos de cobertura y reduce el uso de fertilizantes.',
				'composition' => 'Gluconacetobacter diazotrophicus 4,6 × 10⁸ UFC/ml.',
				'features'    => [
					'Aumenta cannabinoides hasta un 50%',
					'Fijación biológica de nitrógeno atmosférico',
					'Reemplaza cultivos de cobertura',
					'Reduce uso de fertilizantes y aditivos',
					'Optimiza el ROI en producción de cannabinoides',
					'Filtra absorción de metales pesados',
					'Aumenta capacidad de retener humedad',
					'Ayuda a la asimilación del fósforo',
					'Aumenta notablemente el desarrollo radicular',
				],
				'badge'                => 'exclusivo',
				'order'               => 4,
				'image'               => 'logos_productos/logo bioknn.png',
				'dosage'              => [
					'ml_per_liter' => 5,
					'range'        => '5 ml por litro de agua',
					'applications' => 6,
					'timing'       => 'Desde germinación hasta pre-floración, 5 aplicaciones promedio.',
				],
				'application_schedule' => ['stage' => 'vegetativo', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'treemix-a',
				'name'        => 'Treemix A',
				'tagline'     => 'Calidad y producción',
				'short'       => 'Potencia la calidad y el rendimiento del fruto. Fórmula para pre-flora y floración.',
				'description' => 'Bioestimulante de floración que aumenta la producción, el peso e intensifica el sabor. Contiene péptidos biológicos bioactivos de rápida asimilación. Puede combinarse con fertilizantes de otras marcas para potenciar su absorción, y funciona también como biopotenciador de germinación.',
				'composition' => 'Aminoácidos vegetales. Péptidos biológicos bioactivos de rápida asimilación.',
				'features'    => [
					'Aumenta producción, peso e intensidad de sabor',
					'Acorta la distancia internodal',
					'Equilibra el metabolismo',
					'Aumenta el poder germinativo',
					'Evita la propagación de patógenos',
					'Mejora la actividad fotosintética',
					'Potencia permeabilidad celular y absorción de agua',
					'Compatible con fertilizantes de otras marcas',
				],
				'badge'                => 'premium',
				'order'               => 5,
				'image'               => 'logos_productos/LOGO A.png',
				'dosage'              => [
					'ml_per_liter' => 2,
					'range'        => '2 a 4 ml según efecto deseado',
					'applications' => 4,
					'timing'       => '2 aplicaciones radiculares y 2 foliares entre pre-floración y floración.',
				],
				'application_schedule' => ['stage' => 'floracion', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'silicio',
				'name'        => 'Silicio',
				'tagline'     => '100% Eco-friendly',
				'short'       => 'Silicio para tu sustrato. Obtenido a partir de materiales reciclados. Envase compostable.',
				'description' => 'Aporte de silicio bioasimilable que fortalece las paredes celulares, mejora la resistencia frente a estrés hídrico y plagas, y refuerza la estructura general de la planta.',
				'composition' => 'Silicio bioasimilable de origen reciclado.',
				'features'    => [
					'Fortalece paredes celulares',
					'Resistencia a estrés hídrico y plagas',
					'Envase 100% compostable',
					'Origen reciclado',
				],
				'badge'                => 'eco',
				'order'               => 6,
				'image'               => 'logos_productos/SILICIO LOGO-02.png',
				'dosage'              => [
					'ml_per_liter' => 2,
					'range'        => '2 ml por litro de agua',
					'applications' => 4,
					'timing'       => '4 aplicaciones semanales desde inicio de vegetativo.',
				],
				'application_schedule' => ['stage' => 'vegetativo', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'zym',
				'name'        => 'Tree Mix ZYM',
				'tagline'     => 'Bioestimulante enzimático',
				'short'       => 'Acelera la actividad biológica y crecimiento. Enzimas recuperadoras de suelo.',
				'description' => 'Complejo enzimático que activa los microorganismos beneficiosos del sustrato para descomponer restos orgánicos e inorgánicos, transformándolos en nutrientes esenciales. Acelera en horas lo que normalmente lleva días, permite reutilizar el sustrato y ofrece protección contra sobrefertilizaciones accidentales.',
				'composition' => 'Complejo enzimático de origen orgánico.',
				'features'    => [
					'Acelera procesos biológicos: días en horas',
					'Recupera y permite reutilizar el sustrato',
					'Descompone restos orgánicos y sales acumuladas',
					'Potencia el desarrollo radicular',
					'Provee cosechas más abundantes',
					'Protección contra sobrefertilizaciones accidentales',
					'Genera azúcares que estimulan microorganismos',
					'Ceniza blanca limpia en combustión',
				],
				'badge'                => 'premium',
				'order'               => 7,
				'image'               => 'logos_productos/LOGO ZYM.png',
				'dosage'              => [
					'ml_per_liter' => 1,
					'range'        => '1 a 3 ml según efecto deseado',
					'applications' => 'gradual',
					'timing'       => 'Una vez por semana. Optativo en vegetativo, recomendado en floración.',
				],
				'application_schedule' => ['stage' => 'vegetativo', 'frequency' => 'semanal'],
				'dosage_by_stage'      => [
					'vegetativo' => 1,
					'pre-flora'  => 2,
					'floracion'  => 3,
				],
			],
			[
				'slug'        => 'tree-mix-f',
				'name'        => 'Tree Mix F',
				'tagline'     => 'Booster de floración',
				'short'       => 'Estimulante del sistema inmune. Aumenta peso y densidad de los frutos.',
				'description' => 'Actúa sobre el sistema hormonal de la planta a través de la Resistencia Sistémica Inducida. Los inductores fitofortificantes activan el sistema defensivo, mejorando la resistencia a plagas y enfermedades. Contiene altos niveles de fósforo y potasio con propiedades preventivas y curativas.',
				'composition' => 'Fosfito elicitor. Altos niveles de fósforo y potasio.',
				'features'    => [
					'Aumenta peso seco y densidad floral',
					'Resistencia Sistémica Inducida',
					'Efecto vía foliar llega hasta las raíces',
					'Aumenta considerablemente el desarrollo de tricomas',
					'Engrosa tronco, cuello y raíces',
					'Mejora tolerancia al calor y sequías',
					'Propiedades preventivas y curativas contra hongos, virus y bacterias',
					'Excelente complejante de micro y macronutrientes',
				],
				'badge'                => 'floracion',
				'order'               => 8,
				'image'               => 'logos_productos/LOGO F.png',
				'dosage'              => [
					'ml_per_liter' => 2,
					'range'        => '2 a 4 ml por litro de agua',
					'applications' => 4,
					'timing'       => 'En vegetación una dosis, en floración tres dosis.',
				],
				'application_schedule' => ['stage' => 'floracion', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'candy-shock',
				'name'        => 'Shock de Carbohidratos',
				'tagline'     => 'Reemplazo de melazas',
				'short'       => 'Mejora sabor, aroma y vigor. Aumenta rendimiento y peso. 100% orgánico.',
				'description' => 'Mezcla de carbohidratos, vinaza y bioestimulantes que potencia las características organolépticas del producto final. Reemplaza el uso de melazas con un perfil más limpio. Se recomienda combinar con Tree Mix PRO para potenciar la reproducción de vida microbiana en el sustrato.',
				'composition' => 'Carbohidratos, vinaza y bioestimulantes.',
				'features'    => [
					'Mejora sabor y aroma del producto final',
					'Reemplaza el uso de melazas',
					'Potencia reproducción de microorganismos benéficos',
					'Mejora estabilidad física y microbiológica del suelo',
					'Ayuda a la movilidad de nutrientes dentro de la planta',
					'Rápida asimilación',
					'Combinar con PRO para mejores resultados',
				],
				'badge'                => 'organico',
				'order'               => 9,
				'image'               => 'logos_productos/LOGO CANDY.png',
				'dosage'              => [
					'ml_per_liter' => 3,
					'range'        => '3 a 5 ml según efecto deseado',
					'applications' => 4,
					'timing'       => 'No más de una aplicación semanal en etapa de floración.',
				],
				'application_schedule' => ['stage' => 'engorde', 'frequency' => 'semanal'],
			],
			[
				'slug'        => 'biodrop',
				'name'        => 'Tree Mix BioDrop',
				'tagline'     => 'Solución de riego',
				'short'       => 'Tecnología aglutinante de agua y minerales. Hasta 10 días sin regar. Biodegradable.',
				'description' => 'Tecnología aglutinante de agua que genera un reservorio para los cultivos. Una vez agotada el agua del sustrato, las raíces absorben el agua retenida en BioDrop. Libre de derivados del petróleo, sin nutrientes añadidos pero retiene los del sustrato. Vegano, cruelty-free y biodegradable.',
				'composition' => 'Polímero biológico aglutinante. Libre de derivados del petróleo.',
				'features'    => [
					'Hasta 10 días sin regar',
					'Ahorro en nutrientes por retención',
					'Libre de derivados del petróleo',
					'Sin residuos contaminantes',
					'Vegano, cruelty-free y biodegradable',
					'No genera excesos de agua',
					'Superior al hidrogel tradicional',
				],
				'badge'                => 'limitado',
				'order'               => 10,
				'image'               => 'logos_productos/logo biodrop.png',
				'dosage'              => [
					'ml_per_liter' => 0.100,
					'range'        => 'Según tipo de uso (ver tabla)',
					'applications' => 1,
					'timing'       => 'Aplicación puntual junto a las raíces en trasplante.',
				],
				'application_schedule' => ['stage' => 'trasplante', 'frequency' => 'puntual'],
				'biodrop'              => true,
				'dosage_by_use'        => [
					'plantin' => 0.025,
					'tree'    => 0.100,
					'soil'    => 0.800,
				],
			],
			[
				'slug'        => 'kill-mix',
				'name'        => 'Kill Mix',
				'tagline'     => 'Bioinsecticida de contacto',
				'short'       => 'Control biológico de plagas por contacto. Elimina más de 200 especies. 100% orgánico.',
				'description' => 'Biopesticida compuesto por Beauveria bassiana, hongo que parasita al insecto causándole la Enfermedad Blanca de la Muscardina, produciendo su muerte casi instantánea. No genera residuos ni toxicidad y mejora el sistema inmunológico del cultivo una vez eliminada la plaga. Apto en floración.',
				'composition' => 'Beauveria bassiana (hongo entomopatógeno). Genera Beauvericina.',
				'features'    => [
					'Elimina más de 200 especies de insectos',
					'Acción casi instantánea',
					'Sin residuos ni toxicidad',
					'Apto durante todo el ciclo, incluso floración',
					'Mejora el sistema inmune post-exterminación',
					'Amigable con el medio ambiente',
					'Trips, araña roja, pulgones, mosca blanca, ácaros y más',
				],
				'badge'                => 'organico',
				'order'               => 11,
				'image'               => 'logos_productos/LOGO KILL MIX HORIZONTAL.png',
				'dosage'              => [
					'ml_per_liter' => 5,
					'range'        => 'Desde 5 ml según efecto deseado',
					'applications' => 'a demanda',
					'timing'       => 'Mínimo 2 aplicaciones cada 3 a 7 días según variedad de insecto.',
				],
				'application_schedule' => ['stage' => 'todo el ciclo', 'frequency' => 'a demanda'],
			],
			[
				'slug'        => 'kill-bti',
				'name'        => 'Kill BTI',
				'tagline'     => 'Control de sciáridos',
				'short'       => 'Bacillus thuringiensis israelensis. Larvicida orgánico. Ideal para dengue y fungus gnats.',
				'description' => 'Larvicida orgánico que actúa por ingesta produciendo parálisis en las paredes intestinales de los insectos. No daña aves, vida acuática, vegetación ni insectos benéficos. Apto para living soil, hidroponía con larvas, estanques, agua estancada y zonas con riesgo de dengue.',
				'composition' => 'Bacillus thuringiensis var. israelensis.',
				'features'    => [
					'Actúa por ingesta, parálisis intestinal',
					'No daña aves, peces ni insectos benéficos',
					'Apto living soil e hidroponía',
					'Ideal para control de dengue',
					'Aplicable en agua estancada y estanques',
					'Cepa específica para larvas y mosquitos',
				],
				'badge'                => 'organico',
				'order'               => 12,
				'image'               => 'logos_productos/kill bti logo.png',
				'dosage'              => [
					'ml_per_liter' => 2,
					'range'        => '1 a 2 ml cada 10 m² o por litro de agua',
					'applications' => 'a demanda',
					'timing'       => 'En living soil: cada 15 días. En otros métodos: según necesidad.',
				],
				'application_schedule' => ['stage' => 'todo el ciclo', 'frequency' => 'a demanda'],
			],
			[
				'slug'        => 'kit-completo',
				'name'        => 'Kit Treemix Profesional',
				'tagline'     => 'La línea completa',
				'short'       => 'Kit con 5 productos premium: PRO, N, A, F y CANDY. Todo el ciclo cubierto.',
				'description' => 'El kit profesional reúne la línea completa en formato 45 ml. Pensado para cultivadores que buscan resultados consistentes, ciclo tras ciclo, con la fórmula exacta para cada etapa.',
				'composition' => null,
				'features'    => [
					'PRO: estimula y protege',
					'N: complemento vegetativo',
					'A: calidad y producción',
					'F: booster de floración',
					'CANDY: nutrición final',
				],
				'badge'                => 'kit',
				'order'               => 13,
				'image'               => null,
				'dosage'              => [
					'ml_per_liter' => 2,
					'range'        => 'Según cada producto',
					'applications' => 4,
					'timing'       => 'Semanal según etapa; seguir indicaciones de cada producto.',
				],
				'application_schedule' => ['stage' => 'todo el ciclo', 'frequency' => 'semanal'],
			],
		];
	}

	public static function find(string $slug): ?array
	{
		foreach (self::all() as $product) {
			if ($product['slug'] === $slug) {
				return $product;
			}
		}
		return null;
	}
}
